server {
    listen 80;
    server_name _;

    location = /healthz {
        default_type application/json;
        return 200 '{"status":"healthy","application":"helixbridge-dummy"}';
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
